# Generated by Django 4.0.6 on 2024-06-27 03:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id_empr', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empr', models.CharField(max_length=100)),
                ('direccion_empr', models.CharField(max_length=100)),
                ('telefono_empr', models.CharField(max_length=50)),
                ('email_empr', models.CharField(default='', max_length=150)),
                ('fundacion_empr', models.DateField()),
                ('sector_empr', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id_empl', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_empl', models.CharField(max_length=25)),
                ('apellido_empl', models.CharField(default='', max_length=150)),
                ('salario_empl', models.IntegerField()),
                ('puesto_empl', models.CharField(default='', max_length=150)),
                ('foto_empl', models.FileField(blank=True, null=True, upload_to='empleados')),
                ('id_empr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Corporacion.empresas')),
            ],
        ),
    ]
